<?php
// Model to get news for the website
// In reality this would be generated by querying a api/rss feed of a blog that posts updates relating to the framework
// This would be used to potentially notify users of pending updates
/**
 * Created by PhpStorm.
 * User: kai-w
 * Date: 28/03/17
 * Time: 21:09
 */
class WebsiteNewsModel extends AdminModel
{
    private $data;

    public function __construct()
    {
        parent::__construct(get_class($this));
        $this->generateData();
    }

    private function generateData() {
        // This would normally be populated some other way
        $news = array(
            1=>'Your website has been updated! This website is now running an up-to-date version of Kai\'s MVC blogging framework!',
            2=>'You have just reached 200 subscribers! Congratulations on the new subscriber count!',
            3=>'You made your first post!'
        );

        $this->data = $news;
    }

    public function getData() {
        return $this->data;
    }
}