-- Categories
INSERT INTO kwadd001_coursework_2.categories (c_name, c_type) VALUES ('About', 'post');
INSERT INTO kwadd001_coursework_2.categories (c_name, c_type) VALUES ('Default', 'post');
INSERT INTO kwadd001_coursework_2.categories (c_name, c_type) VALUES ('Default Category', 'media');
INSERT INTO kwadd001_coursework_2.categories (c_name, c_type) VALUES ('Header Images', 'media');
INSERT INTO kwadd001_coursework_2.categories (c_name, c_type) VALUES ('Technology', 'post');
INSERT INTO kwadd001_coursework_2.categories (c_name, c_type) VALUES ('Technology', 'media');

-- Contact messages
INSERT INTO kwadd001_coursework_2.contact_messages (cm_name, cm_email, cm_message) VALUES ('Test Name', 'test@company.com', 'This is a test contact message.');

-- Map Markers
INSERT INTO kwadd001_coursework_2.map_markers (mm_name, mm_address, mm_lat, mm_lng, mm_type) VALUES ('Richard Hoggart Building', 'Richard Hoggart Building, Dixon Road, London', 51.4745, -0.035128, 'rhb');
INSERT INTO kwadd001_coursework_2.map_markers (mm_name, mm_address, mm_lat, mm_lng, mm_type) VALUES ('Professor Stuart Hall Building', 'Goldsmiths College, 80 Lewisham Way, London SE14 6NW', 51.4727, -0.037008, 'psh');
INSERT INTO kwadd001_coursework_2.map_markers (mm_name, mm_address, mm_lat, mm_lng, mm_type) VALUES ('Ian Gulland Lecture Theatre', 'London, SE14 6AD', 51.4739, -0.037144, 'igl');

-- Users
INSERT INTO kwadd001_coursework_2.users (u_fname, u_lname, u_dob, u_email, u_password, u_created, u_logins) VALUES ('Default', 'User', '1996-08-13', 'admin@domain.com', 'b2e98ad6f6eb8508dd6a14cfa704bad7f05f6fb1', '2017-04-12 19:14:49', null);
INSERT INTO kwadd001_coursework_2.users (u_fname, u_lname, u_dob, u_email, u_password, u_created, u_logins) VALUES ('John', 'Doe', '1980-04-12', 'john@company.co.uk', 'b2e98ad6f6eb8508dd6a14cfa704bad7f05f6fb1', '2017-04-12 19:17:53', null);

-- Media
INSERT INTO kwadd001_coursework_2.media (u_id, m_title, m_filelocation, m_filename, m_uploaded, m_type, m_size, m_category) VALUES (1, 'Banana Pancakes', 'media/uploads/', 'bananapancakes.jpg', '2017-04-19 15:11:36', 'image/jpeg', '1786026', 4);
INSERT INTO kwadd001_coursework_2.media (u_id, m_title, m_filelocation, m_filename, m_uploaded, m_type, m_size, m_category) VALUES (1, 'Boat on Water', 'media/uploads/', 'boat.jpg', '2017-04-19 15:12:50', 'image/jpeg', '1151572', 4);
INSERT INTO kwadd001_coursework_2.media (u_id, m_title, m_filelocation, m_filename, m_uploaded, m_type, m_size, m_category) VALUES (1, 'Building', 'media/uploads/', 'building.jpg', '2017-04-19 15:24:03', 'image/jpeg', '1851786', 6);
INSERT INTO kwadd001_coursework_2.media (u_id, m_title, m_filelocation, m_filename, m_uploaded, m_type, m_size, m_category) VALUES (1, 'Burger', 'media/uploads/', 'burger.jpg', '2017-04-19 15:25:38', 'image/jpeg', '2523438', 4);
INSERT INTO kwadd001_coursework_2.media (u_id, m_title, m_filelocation, m_filename, m_uploaded, m_type, m_size, m_category) VALUES (1, 'Fish Sticks', 'media/uploads/', 'chips.jpg', '2017-04-19 15:26:18', 'image/jpeg', '2911836', 5);
INSERT INTO kwadd001_coursework_2.media (u_id, m_title, m_filelocation, m_filename, m_uploaded, m_type, m_size, m_category) VALUES (1, 'Dry Hill', 'media/uploads/', 'dry_hill.jpg', '2017-04-19 15:26:56', 'image/jpeg', '2529301', 6);
INSERT INTO kwadd001_coursework_2.media (u_id, m_title, m_filelocation, m_filename, m_uploaded, m_type, m_size, m_category) VALUES (1, 'Primrose', 'media/uploads/', 'flower.jpg', '2017-04-19 15:28:08', 'image/jpeg', '2487035', 5);
INSERT INTO kwadd001_coursework_2.media (u_id, m_title, m_filelocation, m_filename, m_uploaded, m_type, m_size, m_category) VALUES (1, 'Lime', 'media/uploads/', 'lime.jpg', '2017-04-19 15:28:57', 'image/jpeg', '2836370', 4);
INSERT INTO kwadd001_coursework_2.media (u_id, m_title, m_filelocation, m_filename, m_uploaded, m_type, m_size, m_category) VALUES (1, 'Boat on Water1', 'media/uploads/', 'boat.png', '2017-04-26 12:04:45', 'image/png', '7679', 4);
INSERT INTO kwadd001_coursework_2.media (u_id, m_title, m_filelocation, m_filename, m_uploaded, m_type, m_size, m_category) VALUES (1, 'Boat on Water2', 'media/uploads/', 'boat000.png', '2017-04-26 12:10:51', 'image/png', '7822', 4);
INSERT INTO kwadd001_coursework_2.media (u_id, m_title, m_filelocation, m_filename, m_uploaded, m_type, m_size, m_category) VALUES (1, 'Boat on Water3', 'media/uploads/', 'boat1.png', '2017-04-26 12:11:06', 'image/png', '7822', 4);

-- Posts
INSERT INTO kwadd001_coursework_2.posts (u_id, p_title, p_content, p_created, p_category, p_visibility) VALUES (1, 'First Post! Picture post!', 'Hello World! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin libero lorem, suscipit id dui quis, pretium dapibus ex. Vestibulum non lobortis diam, non venenatis mi. Sed pellentesque neque vitae sapien mollis, vel pretium dui maximus. Sed mattis nisi dui, vitae malesuada libero hendrerit sit amet. Duis accumsan tristique sodales. Nunc aliquet dapibus dolor ut posuere. Sed vitae pretium massa, id consectetur tortor. Curabitur ut mauris ut metus laoreet malesuada. Sed dapibus, odio ut malesuada volutpat, tortor sapien volutpat augue, et ultrices augue risus nec mi. Vestibulum id rhoncus risus. Donec ut erat efficitur, dictum risus ut, rhoncus justo. Aenean et nisl tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

<img src=''media/uploads/bananapancakes.jpg'' alt=''Banana Pancakes'' class=''img-responsive''>

Curabitur ac pellentesque metus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam vel eros euismod, fringilla arcu non, ultrices nulla. Fusce eu efficitur lacus, sit amet auctor lectus. Quisque sit amet accumsan justo. Phasellus volutpat eros sed urna pulvinar eleifend. Donec pharetra, massa eget bibendum scelerisque, lacus est pretium tellus, sed dictum purus lectus vitae urna. In tempus et est consequat fermentum. Aenean quis fermentum velit, ut rhoncus tortor. Praesent non turpis ac tellus posuere efficitur quis ac dui. Pellentesque vestibulum augue quis metus elementum, at cursus nisl sagittis. Sed erat nunc, eleifend eget dictum eget, dignissim eget leo. Nam ultricies, justo a finibus eleifend, justo lacus dictum odio, non pretium est massa ac odio. Pellentesque dictum sem risus, nec rhoncus eros egestas rutrum. Nulla odio arcu, vestibulum a maximus a, sodales et ex.

Sed pulvinar leo tortor, sed tincidunt felis tempus vitae. Aliquam dictum, lorem non pharetra consectetur, nisi erat euismod nisl, id accumsan ante orci id enim. Vestibulum varius auctor urna, in euismod augue commodo nec. Proin venenatis turpis elit, vitae porttitor risus vulputate ac. Ut pharetra maximus venenatis. Ut vehicula magna eget felis consectetur, sit amet lobortis nunc blandit. Sed non eros metus. In ultrices, dolor id gravida fringilla, sem ex dictum velit, quis porttitor massa felis eu mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non erat nec felis condimentum maximus id pellentesque massa.', '2017-04-12 19:19:56', 1, 1);
INSERT INTO kwadd001_coursework_2.posts (u_id, p_title, p_content, p_created, p_category, p_visibility) VALUES (1, 'Lorem Ipsum This is a post', 'Some post content right here. Some post content right here. Some post content right here. Some post content right here. Some post content right here. Some post content right here. Some post content right here. Some post content right here. Some post content right here. Some post content right here. Some post content right here. Some post content right here. Some post content right here. Some post content right here. Some post content right here. Some post content right here. Some post content right here. Some post content right here. Some post content right here. 

<img src=''media/uploads/building.jpg'' alt=''Building'' class=''img-responsive''>

More content after.', '2017-04-19 15:39:30', 2, 1);
INSERT INTO kwadd001_coursework_2.posts (u_id, p_title, p_content, p_created, p_category, p_visibility) VALUES (1, 'Pirate Ipsum', 'Shiver me timbers lad clipper yardarm matey jury mast lookout lanyard haul wind list heave down lateen sail crack Jennys tea cup gangway Blimey Admiral of the Black Jolly Roger yawl doubloon port weigh anchor barque warp Pirate Round jolly boat bring a spring upon her cable rigging aft marooned walk the plank poop deck come about wench take a caulk dead men tell no tales long boat clap of thunder line jib rutters black spot American Main hardtack tackle gibbet skysail cackle fruit scourge of the seven seas chase tender. Rutters sheet tender execution dock bounty come about keel chase guns red ensign pirate gangway handsomely tackle bucko bilge rat code of conduct trysail hempen halter barque brigantine yo-ho-ho Jack Tar sutler no prey, no pay Nelsons folly overhaul league bilge hornswaggle prow jury mast heave down gangplank brig six pounders avast booty crimp Pirate Round line pillage jack topgallant crack Jennys tea cup Buccaneer chandler warp pink gally fathom. Gangplank fire in the hole clipper bucko chase guns chantey coffer pirate gaff killick league scurvy transom marooned aft lee topgallant lugsail doubloon swing the lead driver bowsprit American Main bounty heave to lugger strike colors heave down cable splice the main brace tack hardtack Brethren of the Coast Davy Jones'' Locker booty loot smartly schooner run a rig Letter of Marque hempen halter log sutler Jack Tar topmast draught reef sails gibbet come about mutiny.

Capstan killick Corsair lateen sail take a caulk quarterdeck avast run a shot across the bow hornswaggle bounty clap of thunder main sheet dead men tell no tales topmast bring a spring upon her cable poop deck Blimey fore come about snow Jack Ketch crack Jennys tea cup chase mizzenmast mutiny ho pinnace log cog line fire in the hole jolly boat gibbet piracy lanyard no prey, no pay dance the hempen jig gangway clipper case shot bowsprit driver Nelsons folly Gold Road Yellow Jack keel yawl lad lookout scuppers. Red ensign Sink me spyglass Chain Shot Yellow Jack knave hogshead interloper fluke yo-ho-ho barkadeer measured fer yer chains wherry hang the jib crow''s nest scallywag aye six pounders provost trysail black jack prow cog bilge water killick log man-of-war plunder Privateer stern square-rigged gangplank bilge rat bucko matey spanker snow mutiny pressgang case shot draft black spot Jack Ketch loaded to the gunwalls Shiver me timbers overhaul quarter Letter of Marque blow the man down careen. Black spot squiffy starboard Cat o''nine tails to go on account ye pressgang walk the plank haul wind pirate mutiny stern crack Jennys tea cup snow brig swab matey keelhaul fathom hempen halter Spanish Main barkadeer lass tender mizzen tack draft port no prey, no pay Admiral of the Black boom spyglass brigantine warp keel man-of-war cog sutler landlubber or just lubber grog gunwalls bowsprit chase prow spanker lad blow the man down American Main code of conduct chandler.

Parley run a rig landlubber or just lubber code of conduct bilge water furl grapple capstan chase lass interloper piracy man-of-war rope''s end gally Spanish Main holystone loaded to the gunwalls snow shrouds scourge of the seven seas Yellow Jack belaying pin Brethren of the Coast bounty chandler hornswaggle barkadeer topgallant bring a spring upon her cable quarterdeck stern galleon pinnace spanker run a shot across the bow strike colors draft grog blossom flogging jury mast clap of thunder ahoy coffer list booty skysail driver Sea Legs marooned. Long clothes knave hang the jib chantey keel stern cog gangplank list interloper matey landlubber or just lubber run a rig topgallant gangway hands Jack Ketch bilge water Arr starboard scuttle poop deck code of conduct walk the plank mutiny deadlights Buccaneer broadside booty squiffy pressgang Brethren of the Coast crimp bring a spring upon her cable galleon chase bilge furl bilge rat barque Letter of Marque lad gibbet snow fluke brig six pounders bucko pillage jack. Doubloon keelhaul rutters hail-shot gally fire ship scurvy measured fer yer chains squiffy lugger to go on account heave down Buccaneer dead men tell no tales bounty red ensign grog blossom rope''s end Pirate Round chandler parrel parley Admiral of the Black galleon tackle lad matey keel pinnace hands spyglass hempen halter loaded to the gunwalls capstan line code of conduct Pieces of Eight ahoy hornswaggle smartly prow quarterdeck hulk booty gibbet port shrouds American Main cable league.

Clap of thunder provost Jack Ketch swing the lead coffer parrel line gaff fore jury mast driver topgallant bowsprit jolly boat scurvy Gold Road tack aft blow the man down league long boat to go on account black spot hulk run a shot across the bow dead men tell no tales list Cat o''nine tails starboard bilge rat rope''s end barque booty chandler bring a spring upon her cable parley wherry Davy Jones'' Locker Admiral of the Black gunwalls Sea Legs wench lugger Yellow Jack Brethren of the Coast pinnace Arr fathom yard tackle. Plunder log Barbary Coast sloop scallywag lugsail belay jib clap of thunder ahoy topgallant chase Cat o''nine tails lass square-rigged rigging dance the hempen jig American Main boatswain warp heave down skysail piracy marooned mizzen brig blow the man down take a caulk fire in the hole rutters Buccaneer code of conduct Corsair bilge yard furl boom Pirate Round six pounders hearties cog lateen sail brigantine careen to go on account yo-ho-ho black jack jolly boat tack pillage. Interloper poop deck pink walk the plank barque Spanish Main Sail ho chase guns hornswaggle yard Brethren of the Coast loaded to the gunwalls sloop Cat o''nine tails bring a spring upon her cable heave down reef run a shot across the bow schooner handsomely quarter Pirate Round come about careen pillage killick chase lanyard splice the main brace Sink me bilged on her anchor pressgang Arr lad grog blossom Shiver me timbers provost barkadeer blow the man down boatswain Corsair lateen sail measured fer yer chains yawl draught squiffy furl case shot crimp hardtack.', '2017-04-19 15:41:04', 1, 1);